package com.tqs.hw1;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logintest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1024, 546));
    driver.findElement(By.id("location")).sendKeys("London");
    driver.findElement(By.id("location")).sendKeys(Keys.ENTER);
    String city = driver.findElement(By.id("city")).getText();
    assertThat("London", is(city));
    driver.findElement(By.id("location")).sendKeys("Aveiro");
    driver.findElement(By.id("location")).sendKeys(Keys.ENTER);
    city = driver.findElement(By.id("city")).getText();
    assertThat("Informação do local é inexistente.", is(city));

  }
}
